version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: drf_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../backend/webstore/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: drf_db
    env_file:
      - ../backend/webstore/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
